version: '3.8'
services:
  gateway:
    build: shareit-gateway
    image: shareit-gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ser
    image: shareit-server-image
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver #org.h2.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_db  #jdbc:h2:mem:my_db
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test

  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:14-alpine
    container_name: my_app-db
    ports:
      - "5434:5432"
    # переменные окружения
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

